'use client'

import { useState, useEffect, useCallback } from "react";
import { Shield, Server, MessageSquare, AlertTriangle, CheckCircle, Clock, Zap, Bot, Rocket, ChevronRight, Monitor, Database, Globe, Mail, Terminal, Users, DollarSign, Activity, RefreshCw, HelpCircle, Layers, Wifi, WifiOff, BarChart3, PieChart, Cpu } from "lucide-react";

const DASHBOARD_STATUS = {
  timestamp: new Date().toISOString(),
  live: false,
  malaysia: {
    name: "Malaysia Dev",
    ip: "72.62.252.232",
    location: "Malaysia",
    resources: { cpu: 38, memory: 61, disk: 44, diskFreeGb: 224, memTotalGb: 32, memUsedGb: 19.5 },
    services: [
      { name: "CRM", status: "down", port: 3000, owner: "Smarty", runtime: "PM2", priority: "critical", note: "Core CRM production app" },
      { name: "Command Center", status: "down", port: 3001, owner: "Smarty", runtime: "Docker", priority: "critical", note: "OpenClaw command center" },
      { name: "smarterrevolutionai.com", status: "degraded", port: 3003, owner: "Smarty", runtime: "PM2", priority: "high", note: "Legacy public website" },
      { name: "Smarter Studio prod", status: "degraded", port: 3004, owner: "Orion", runtime: "systemd", priority: "high", note: "Primary Smarter Studio production app" },
      { name: "Executive Dashboard", status: "up", port: 3006, owner: "Smarty", runtime: "PM2", priority: "medium", note: "Executive operations dashboard" },
      { name: "Smarter Studio staging", status: "up", port: 3012, owner: "Orion", runtime: "systemd", priority: "medium", note: "Staging environment" },
      { name: "Texican staging", status: "up", port: 3010, owner: "Orion", runtime: "systemd", priority: "medium", note: "Texican staging app" },
      { name: "CRM PostgreSQL", status: "up", port: 5432, owner: "Smarty", runtime: "Docker", priority: "critical", note: "Primary CRM database" },
      { name: "Redis", status: "up", port: 6379, owner: "Smarty", runtime: "Docker", priority: "high", note: "Shared cache" },
      { name: "Qdrant", status: "up", port: 6333, owner: "Smarty", runtime: "Docker", priority: "high", note: "Vector database" },
      { name: "Ollama", status: "up", port: 11434, owner: "Smarty", runtime: "Docker", priority: "high", note: "Agent brain / local inference" },
      { name: "Texican PostgreSQL", status: "up", port: 5433, owner: "Orion", runtime: "Docker", priority: "medium", note: "Texican staging database" },
      { name: "Sales automation scripts", status: "up", port: "cron", owner: "Smarty", runtime: "cron", priority: "medium", note: "Sales automation jobs" },
      { name: "Warm Lead Engine", status: "up", port: "cron", owner: "Smarty", runtime: "cron", priority: "medium", note: "Lead reply scanning and draft pipeline" },
      { name: "3 Python workers", status: "up", port: "worker", owner: "Orion", runtime: "Python workers", priority: "medium", note: "Background workers for Orion stack" },
      { name: "13 OpenClaw cron jobs", status: "up", port: "cron", owner: "Orion", runtime: "OpenClaw cron", priority: "medium", note: "Automated Orion workflows" },
    ]
  },
  us: {
    name: "US Production",
    ip: "76.13.121.142",
    location: "USA",
    status: "Ready for migration",
    resources: { cpu: 11, memory: 29, disk: 18, diskFreeGb: 78, memTotalGb: 8, memUsedGb: 2.3 },
    databases: [
      { name: "PostgreSQL A", status: "up" },
      { name: "PostgreSQL B", status: "up" },
      { name: "Redis", status: "up" },
      { name: "Qdrant", status: "up" },
    ],
    notes: [
      "Configured, ready for migration",
      "Database containers up (PostgreSQL x2, Redis, Qdrant)",
      "Node.js, PM2, Nginx, Docker installed",
      "Waiting on Phase 4 completion before migration begins",
    ]
  },
  backup: { name: "Malaysia Backup", ip: "187.77.130.210", location: "Malaysia", status: "Standby / DR" }
};

const DEMO_COSTS = { today:{total:4.82,smarty:3.15,optimus:1.67}, week:{total:18.45,smarty:12.30,optimus:6.15}, month:{total:52.30,smarty:38.20,optimus:14.10}, byModel:[{model:"Claude Opus 4.6",cost:18.5},{model:"Claude Sonnet 4.5",cost:14.2},{model:"Claude Haiku 4.5",cost:3.8},{model:"GPT-5-nano",cost:0.45}], daily:[{date:"Apr 2",total:5.2},{date:"Apr 3",total:6.8},{date:"Apr 4",total:4.1},{date:"Apr 5",total:7.9},{date:"Apr 6",total:5.5},{date:"Apr 7",total:4.35},{date:"Apr 8",total:4.82}], infra:{vps:25,external:12,total:37} };
const ROLLOUT_PHASES = [
  { phase:"A", title:"Inventory", status:"complete", desc:"Complete" },
  { phase:"B", title:"Branching", status:"complete", desc:"Complete" },
  { phase:"B.5", title:"Sage Integration", status:"degraded", desc:"Context provided, intermittently offline" },
  { phase:"3", title:"Monitoring", status:"complete", desc:"Complete" },
  { phase:"4", title:"CI/CD Pipeline", status:"active", desc:"Pipeline built, awaiting test" },
  { phase:"5", title:"Production Migration to US", status:"pending", desc:"Not started, blocked on Phase 4" },
];
const SERVER_INVENTORY = [
  { name:"US Production", ip:"76.13.121.142", plan:"KVM 2", cpu:"2 vCPU", memory:"8GB", disk:"100GB", location:"USA", status:"Configured, ready for migration" },
  { name:"Malaysia Dev", ip:"72.62.252.232", plan:"KVM 8", cpu:"8 vCPU", memory:"32GB", disk:"400GB", location:"Malaysia", status:"Active, all services" },
  { name:"Malaysia Backup", ip:"187.77.130.210", plan:"KVM 4", cpu:"4 vCPU", memory:"16GB", disk:"200GB", location:"Malaysia", status:"Standby" },
];
const CHANNELS = [{ name:"#exec-dashboard", icon:Monitor, color:"text-blue-400", desc:"Daily and weekly reports.", action:"Read daily." },{ name:"#alerts-critical", icon:AlertTriangle, color:"text-red-400", desc:"Urgent incidents and outages.", action:"Respond when pinged." },{ name:"#deployment-log", icon:Rocket, color:"text-amber-400", desc:"PRs and deploy approvals.", action:"React ✅ or ❌." },{ name:"#requests", icon:MessageSquare, color:"text-emerald-400", desc:"Give instructions here.", action:"Where you give orders." }];
const COMMANDS = [{ cmd:"What's the status of everything?", who:"@Optimus", result:"Full system health report" },{ cmd:"What is Smarty working on?", who:"@Smarty", result:"Current projects and progress" },{ cmd:"Is the CRM running ok?", who:"@Optimus", result:"Health check with response times" }];
const GLOSSARY = [{ term:"VPS", plain:"A cloud server where your software runs." },{ term:"PM2", plain:"A process manager that restarts crashed apps." },{ term:"CI/CD Pipeline", plain:"Automation that tests and deploys code." },{ term:"Cron Job", plain:"A scheduled task that runs automatically." }];
const SVC_ICONS = { CRM: Users, "Command Center": Terminal, "smarterrevolutionai.com": Globe, "Executive Dashboard": Monitor, "Smarter Studio prod": Rocket, "Smarter Studio staging": Rocket, "Texican staging": Globe, "CRM PostgreSQL": Database, Redis: Database, Qdrant: Database, Ollama: Cpu, "Texican PostgreSQL": Database, "Sales automation scripts": Zap, "Warm Lead Engine": Mail, "3 Python workers": Activity, "13 OpenClaw cron jobs": Clock };
const tabs = [{ id:"status", label:"Live Status", icon:Activity },{ id:"costs", label:"Cost Tracking", icon:DollarSign },{ id:"overview", label:"Servers", icon:Layers },{ id:"agents", label:"Agents", icon:Bot },{ id:"services", label:"Services", icon:Server },{ id:"rollout", label:"Rollout Plan", icon:Rocket },{ id:"discord", label:"Discord Guide", icon:MessageSquare },{ id:"commands", label:"Commands", icon:Terminal },{ id:"decisions", label:"Your Decisions", icon:CheckCircle },{ id:"glossary", label:"Glossary", icon:HelpCircle }];

const Badge = ({ children, variant = "default" }) => { const s = { critical:"bg-red-500/20 text-red-400 border-red-500/30", high:"bg-amber-500/20 text-amber-400 border-amber-500/30", medium:"bg-emerald-500/20 text-emerald-400 border-emerald-500/30", up:"bg-emerald-500/20 text-emerald-400 border-emerald-500/30", down:"bg-red-500/20 text-red-400 border-red-500/30", degraded:"bg-amber-500/20 text-amber-400 border-amber-500/30", active:"bg-emerald-500/20 text-emerald-400 border-emerald-500/30", pending:"bg-zinc-700/50 text-zinc-400 border-zinc-600/30", complete:"bg-blue-500/20 text-blue-400 border-blue-500/30", default:"bg-zinc-700/50 text-zinc-300 border-zinc-600/30", Smarty:"bg-violet-500/20 text-violet-300 border-violet-500/30", Optimus:"bg-cyan-500/20 text-cyan-300 border-cyan-500/30" }; return <span className={`px-2 py-0.5 rounded-full text-xs font-medium border ${s[variant]||s.default}`}>{children}</span>; };
const Card = ({ children, className = "" }) => <div className={`bg-gradient-to-br from-zinc-800 to-zinc-900 rounded-xl border border-zinc-700/50 ${className}`}>{children}</div>;
const ProgressBar = ({ value, max = 100, color = "emerald", size = "md" }) => { const c = value > 90 ? "red" : value > 80 ? "amber" : color; const colors = { emerald:"from-emerald-500 to-cyan-500", amber:"from-amber-500 to-orange-500", red:"from-red-500 to-rose-500", blue:"from-blue-500 to-indigo-500", violet:"from-violet-500 to-purple-500", cyan:"from-cyan-500 to-blue-500" }; return <div className={`w-full bg-zinc-700 rounded-full overflow-hidden ${size==="sm"?"h-1.5":"h-3"}`}><div className={`bg-gradient-to-r ${colors[c]||colors.emerald} h-full rounded-full transition-all duration-500`} style={{width:`${Math.min(value,max)/max*100}%`}}/></div>; };

export default function Dashboard() {
  const [tab, setTab] = useState("status");
  const [status, setStatus] = useState(DASHBOARD_STATUS);
  const [costs, setCosts] = useState(DEMO_COSTS);
  const [isLive, setIsLive] = useState(false);
  const [expGloss, setExpGloss] = useState(null);
  const fetchData = useCallback(async () => { try { const r = await fetch("/api/system-status"); if (r.ok) { const d = await r.json(); setStatus({...DASHBOARD_STATUS, ...d, live:true}); setIsLive(true); } } catch { setIsLive(false); } try { const r = await fetch("/api/cost-tracking"); if (r.ok) setCosts(await r.json()); } catch {} }, []);
  useEffect(() => { fetchData(); const i = setInterval(fetchData, 60000); return () => clearInterval(i); }, [fetchData]);

  const renderStatus = () => <div className="space-y-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2">{isLive ? <Wifi className="w-4 h-4 text-emerald-400"/> : <WifiOff className="w-4 h-4 text-zinc-500"/>}<span className={`text-xs ${isLive?"text-emerald-400":"text-zinc-500"}`}>{isLive ? "Live API connected" : "Dashboard baseline view"}</span></div><button onClick={fetchData} className="text-xs text-zinc-400 hover:text-white flex items-center gap-1"><RefreshCw className="w-3 h-3"/>Refresh</button></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{[status.malaysia, status.us].map(server => <Card key={server.ip} className="p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="text-lg font-bold text-white">{server.name}</h3><p className="text-sm text-zinc-400">{server.ip} · {server.location}</p></div>{server.status && <Badge variant="complete">{server.status}</Badge>}</div><div className="space-y-4"><div><div className="flex justify-between text-sm mb-1"><span className="text-zinc-300">CPU</span><span className="text-white font-medium">{server.resources.cpu}%</span></div><ProgressBar value={server.resources.cpu}/></div><div><div className="flex justify-between text-sm mb-1"><span className="text-zinc-300">Memory</span><span className="text-white font-medium">{server.resources.memory}%</span></div><ProgressBar value={server.resources.memory}/><div className="text-xs text-zinc-500 mt-0.5">{server.resources.memUsedGb}GB / {server.resources.memTotalGb}GB</div></div><div><div className="flex justify-between text-sm mb-1"><span className="text-zinc-300">Disk</span><span className="text-white font-medium">{server.resources.disk}%</span></div><ProgressBar value={server.resources.disk}/><div className="text-xs text-zinc-500 mt-0.5">{server.resources.diskFreeGb}GB free</div></div></div></Card>)}</div><Card className="p-5"><h4 className="text-sm font-semibold text-zinc-400 mb-3 flex items-center gap-2"><Database className="w-4 h-4"/>US Production Database Containers</h4><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{status.us.databases.map(db => <div key={db.name} className="flex items-center justify-between p-3 rounded-lg bg-zinc-900/50 border border-zinc-700/30"><span className="text-sm text-white">{db.name}</span><Badge variant={db.status}>{db.status.toUpperCase()}</Badge></div>)}</div></Card></div>;
  const renderCosts = () => { const maxDaily = Math.max(...costs.daily.map(d=>d.total)); const sortedModels = [...costs.byModel].sort((a,b)=>b.cost-a.cost); const totalModelCost = sortedModels.reduce((a,m)=>a+m.cost,0); return <div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[{ label:"Today", val:`$${costs.today.total.toFixed(2)}`, sub:`S: $${costs.today.smarty.toFixed(2)} · O: $${costs.today.optimus.toFixed(2)}` },{ label:"This Week", val:`$${costs.week.total.toFixed(2)}`, sub:`S: $${costs.week.smarty.toFixed(2)} · O: $${costs.week.optimus.toFixed(2)}` },{ label:"This Month", val:`$${costs.month.total.toFixed(2)}`, sub:`S: $${costs.month.smarty.toFixed(2)} · O: $${costs.month.optimus.toFixed(2)}` },{ label:"Infra (Monthly)", val:`$${costs.infra.total}/mo`, sub:`VPS: $${costs.infra.vps} · Services: $${costs.infra.external}` }].map((c,i) => <Card key={i} className="p-4 text-center"><div className="text-xs text-zinc-400 mb-1">{c.label}</div><div className="text-2xl font-bold text-white">{c.val}</div><div className="text-xs text-zinc-500 mt-1">{c.sub}</div></Card>)}</div><Card className="p-5"><h4 className="text-sm font-semibold text-zinc-400 mb-4 flex items-center gap-2"><BarChart3 className="w-4 h-4"/>Daily API Spend</h4><div className="flex items-end gap-2 h-40">{costs.daily.map((d,i) => <div key={i} className="flex-1 flex flex-col items-center gap-1"><span className="text-xs text-zinc-400">${d.total.toFixed(0)}</span><div className="w-full bg-zinc-700 rounded-t-md overflow-hidden flex flex-col justify-end" style={{height:"120px"}}><div className="bg-gradient-to-t from-cyan-500 to-violet-500 rounded-t-md" style={{height:`${(d.total/maxDaily)*100}%`}}/></div><span className="text-xs text-zinc-500">{d.date}</span></div>)}</div></Card><Card className="p-5"><h4 className="text-sm font-semibold text-zinc-400 mb-4 flex items-center gap-2"><PieChart className="w-4 h-4"/>Cost by Model</h4><div className="space-y-2">{sortedModels.map((m,i) => <div key={i} className="flex items-center gap-3 p-2 rounded-lg bg-zinc-900/50"><div className="w-32 text-sm text-zinc-300 font-medium truncate">{m.model}</div><div className="flex-1"><ProgressBar value={m.cost} max={totalModelCost} color={i<2?"violet":"cyan"} size="sm"/></div><div className="w-16 text-right text-sm text-white font-medium">${m.cost.toFixed(2)}</div></div>)}</div></Card></div>; };
  const renderOverview = () => <div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{SERVER_INVENTORY.map(server => <Card key={server.ip} className="p-5"><div className="flex items-center gap-3 mb-3"><div className="p-2 rounded-lg bg-cyan-500/10"><Server className="w-5 h-5 text-cyan-300"/></div><div><div className="text-sm text-zinc-400">{server.location}</div><div className="text-lg font-semibold text-white">{server.name}</div></div></div><div className="space-y-1 text-sm text-zinc-300"><div>{server.ip}</div><div>{server.plan} · {server.cpu} · {server.memory} · {server.disk}</div><div className="text-zinc-400">{server.status}</div></div></Card>)}</div></div>;
  const renderAgents = () => <div className="space-y-5">{[{ name:"Smarty", role:"Development agent", manager:"Mark", summary:"Operational", icon:Bot, cHex:"#a78bfa", bg:"rgba(139,92,246,0.1)", status:"active" },{ name:"Optimus", role:"Production guardian", manager:"Mark", summary:"Operational, has access to both Malaysia and US servers", icon:Shield, cHex:"#22d3ee", bg:"rgba(6,182,212,0.1)", status:"active" },{ name:"Orion", role:"Development agent", manager:"Wolf", summary:"Operational", icon:Rocket, cHex:"#f59e0b", bg:"rgba(245,158,11,0.1)", status:"active" },{ name:"Sage", role:"Development + coordination", manager:"Wolf and Mark", summary:"Intermittently offline", icon:Layers, cHex:"#10b981", bg:"rgba(16,185,129,0.1)", status:"degraded" }].map(a => <Card key={a.name} className="p-6"><div className="flex items-center gap-3 mb-2"><div className="p-3 rounded-xl" style={{background:a.bg}}><a.icon className="w-7 h-7" style={{color:a.cHex}}/></div><div className="flex-1"><h3 className="text-xl font-bold text-white">{a.name}</h3><p className="text-sm" style={{color:a.cHex}}>{a.role}</p></div><Badge variant={a.status}>{a.status}</Badge></div><div className="text-sm text-zinc-300">Managed by {a.manager}</div><div className="text-sm text-zinc-400 mt-1">{a.summary}</div></Card>)}</div>;
  const renderServices = () => <div className="space-y-5"><Card className="p-5"><div className="flex items-center justify-between mb-3"><div><h3 className="text-white font-semibold">Malaysia VPS</h3><p className="text-sm text-zinc-400">72.62.252.232 · active service host</p></div><Badge variant="high">All live services</Badge></div><div className="space-y-3">{status.malaysia.services.map(s => { const I = SVC_ICONS[s.name] || Server; return <div key={s.name} className="p-4 rounded-xl border border-zinc-700/40 bg-zinc-900/50"><div className="flex items-start gap-3"><div className="p-2 bg-zinc-700/50 rounded-lg"><I className="w-5 h-5 text-zinc-300"/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2 mb-1"><span className="text-white font-semibold">{s.name}</span><Badge variant={s.priority}>{s.priority.toUpperCase()}</Badge><Badge variant={s.status}>{s.status.toUpperCase()}</Badge><span className="text-xs text-zinc-500">:{s.port}</span></div><div className="text-sm text-zinc-400">{s.runtime} · owner: {s.owner}</div><div className="text-sm text-zinc-300 mt-1">{s.note}</div></div></div></div>; })}</div></Card><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Card className="p-5"><h3 className="text-white font-semibold mb-2">US Production Server</h3><p className="text-sm text-zinc-400 mb-3">76.13.121.142 · configured, no services migrated yet</p><div className="space-y-2 text-sm text-zinc-300"><div>Status: <span className="text-emerald-400">Ready for migration</span></div><div>Database containers up: PostgreSQL x2, Redis, Qdrant</div><div>Node.js, PM2, Nginx, Docker installed</div><div>Waiting on Phase 4 completion before migration begins</div></div></Card><Card className="p-5"><h3 className="text-white font-semibold mb-2">Malaysia Backup Server</h3><p className="text-sm text-zinc-400 mb-3">187.77.130.210</p><div className="text-sm text-zinc-300">Status: Standby / DR</div></Card></div></div>;
  const renderRollout = () => <div className="space-y-3">{ROLLOUT_PHASES.map(p => <Card key={p.phase} className={p.status==="active"?"border-emerald-500/30":""}><div className="w-full p-4 text-left flex items-center justify-between"><div className="flex items-center gap-3"><div className={`w-10 h-10 rounded-lg flex items-center justify-center text-lg font-bold ${p.status==="active"?"bg-emerald-500/20 text-emerald-400":p.status==="complete"?"bg-blue-500/20 text-blue-400":p.status==="degraded"?"bg-amber-500/20 text-amber-400":"bg-zinc-700/50 text-zinc-400"}`}>{p.phase}</div><div><div className="text-white font-semibold flex items-center gap-2">{p.title} <Badge variant={p.status}>{p.status}</Badge></div><div className="text-sm text-zinc-400">{p.desc}</div></div></div></div></Card>)}</div>;
  const renderDiscord = () => <div className="space-y-3">{CHANNELS.map(ch => <Card key={ch.name} className="p-4"><div className="flex items-center gap-3 mb-1.5"><ch.icon className={`w-5 h-5 ${ch.color}`}/><span className="text-white font-semibold">{ch.name}</span></div><p className="text-sm text-zinc-300 ml-8">{ch.desc}</p><p className="text-sm mt-1.5 ml-8 font-medium text-emerald-400">→ {ch.action}</p></Card>)}</div>;
  const renderCommands = () => <div className="space-y-3">{COMMANDS.map((c,i) => <Card key={i} className="p-3"><div className="flex items-start gap-3"><Terminal className="w-4 h-4 text-emerald-400 mt-1 shrink-0"/><div className="flex-1"><p className="text-white font-mono text-sm">"{c.cmd}"</p><div className="flex items-center gap-2 mt-1.5"><Badge variant={c.who.replace("@","")}>{c.who}</Badge><span className="text-xs text-zinc-400">→ {c.result}</span></div></div></div></Card>)}</div>;
  const renderDecisions = () => <div className="space-y-3">{[{ type:"Deployment Approval", ch:"#deployment-log", freq:"Few times/week", how:"React ✅ or ❌.", tip:"Ask @Optimus if unsure." },{ type:"Infrastructure Spending", ch:"#exec-dashboard", freq:"Rare", how:"Reply to approve.", tip:"Optimus does not spend without approval." }].map((d,i) => <Card key={i} className="p-4"><div className="flex items-center justify-between mb-1.5"><span className="text-white font-semibold">{d.type}</span><span className="text-xs text-zinc-500 bg-zinc-700/50 px-2 py-0.5 rounded-full">{d.freq}</span></div><p className="text-sm text-zinc-300">{d.how}</p><p className="text-xs text-zinc-500 mt-1">Channel: <strong className="text-zinc-400">{d.ch}</strong></p><div className="mt-2 bg-zinc-900/50 rounded p-2 border border-zinc-700/30"><p className="text-xs text-amber-300">💡 {d.tip}</p></div></Card>)}</div>;
  const renderGlossary = () => <div className="space-y-1.5">{GLOSSARY.map((g,i) => <button key={i} onClick={()=>setExpGloss(expGloss===i?null:i)} className="w-full text-left bg-zinc-800/80 rounded-lg border border-zinc-700/50 p-3 hover:border-zinc-600/50 transition-colors"><div className="flex items-center justify-between"><span className="text-white font-medium text-sm">{g.term}</span><ChevronRight className={`w-4 h-4 text-zinc-400 transition-transform ${expGloss===i?"rotate-90":""}`}/></div>{expGloss===i && <p className="text-sm text-zinc-400 mt-2 border-t border-zinc-700/30 pt-2">{g.plain}</p>}</button>)}</div>;
  const renderers = { status:renderStatus, costs:renderCosts, overview:renderOverview, agents:renderAgents, services:renderServices, rollout:renderRollout, discord:renderDiscord, commands:renderCommands, decisions:renderDecisions, glossary:renderGlossary };
  return <div className="min-h-screen bg-zinc-950 text-white"><div className="bg-gradient-to-r from-zinc-900 via-zinc-800 to-zinc-900 border-b border-zinc-700/50"><div className="max-w-6xl mx-auto px-4 py-4"><div className="flex items-center gap-3"><div className="p-2 bg-gradient-to-br from-violet-500/30 to-cyan-500/30 rounded-xl"><Zap className="w-6 h-6 text-white"/></div><div><h1 className="text-xl font-bold">OpenClaw Executive Dashboard</h1><p className="text-sm text-zinc-400">Smarter Revolution · Dual-Agent Operations</p></div><div className="ml-auto flex items-center gap-2"><div className={`w-2 h-2 rounded-full ${isLive?"bg-emerald-400 animate-pulse":"bg-zinc-500"}`}/><span className="text-xs text-zinc-400">{isLive?"Live":"Baseline"}</span></div></div></div></div><div className="max-w-6xl mx-auto px-4 py-4"><div className="flex gap-1 overflow-x-auto pb-2 mb-5 border-b border-zinc-800">{tabs.map(t => <button key={t.id} onClick={()=>setTab(t.id)} className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-colors ${tab===t.id?"bg-zinc-800 text-white":"text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800/50"}`}><t.icon className="w-4 h-4"/>{t.label}</button>)}</div>{renderers[tab]?.()}</div></div>;
}
